// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for EvaluationResultStatus.
const (
	EvaluationResultStatusCompleted  EvaluationResultStatus = "completed"
	EvaluationResultStatusEvaluating EvaluationResultStatus = "evaluating"
	EvaluationResultStatusFailed     EvaluationResultStatus = "failed"
	EvaluationResultStatusPending    EvaluationResultStatus = "pending"
)

// Defines values for OfferEvaluationStatus.
const (
	OfferEvaluationStatusEvaluated    OfferEvaluationStatus = "evaluated"
	OfferEvaluationStatusEvaluating   OfferEvaluationStatus = "evaluating"
	OfferEvaluationStatusFailed       OfferEvaluationStatus = "failed"
	OfferEvaluationStatusNotEvaluated OfferEvaluationStatus = "not_evaluated"
)

// Defines values for OfferLaunchStatus.
const (
	Launched    OfferLaunchStatus = "launched"
	Launching   OfferLaunchStatus = "launching"
	NotLaunched OfferLaunchStatus = "not_launched"
	Paused      OfferLaunchStatus = "paused"
)

// Defines values for OfferSimulationStatus.
const (
	Failed       OfferSimulationStatus = "failed"
	NotSimulated OfferSimulationStatus = "not_simulated"
	Simulated    OfferSimulationStatus = "simulated"
	Simulating   OfferSimulationStatus = "simulating"
)

// Defines values for OfferStatus.
const (
	Archived   OfferStatus = "archived"
	Evaluating OfferStatus = "evaluating"
	Optimizing OfferStatus = "optimizing"
	Scaling    OfferStatus = "scaling"
)

// Defines values for OfferStatusUpdatedStatus.
const (
	Ok OfferStatusUpdatedStatus = "ok"
)

// Defines values for InitializeDemoDataJSONBodyModules.
const (
	AdsAccounts InitializeDemoDataJSONBodyModules = "ads_accounts"
	Offers      InitializeDemoDataJSONBodyModules = "offers"
	Tasks       InitializeDemoDataJSONBodyModules = "tasks"
)

// DemoInitializeResponse defines model for DemoInitializeResponse.
type DemoInitializeResponse struct {
	DemoCounts         map[string]int `json:"demo_counts"`
	InitializedModules []string       `json:"initialized_modules"`
	SkippedModules     []string       `json:"skipped_modules"`
	Success            bool           `json:"success"`
}

// DemoStatusResponse defines model for DemoStatusResponse.
type DemoStatusResponse struct {
	Modules map[string]struct {
		DemoCount   int  `json:"demo_count"`
		HasRealData bool `json:"has_real_data"`
		RealCount   int  `json:"real_count"`
	} `json:"modules"`
}

// Error defines model for Error.
type Error struct {
	Error *struct {
		Code    string      `json:"code"`
		Details interface{} `json:"details,omitempty"`
		Message string      `json:"message"`
		TraceId *string     `json:"traceId,omitempty"`
	} `json:"error,omitempty"`
}

// EvaluationResult defines model for EvaluationResult.
type EvaluationResult struct {
	BrandName      *string   `json:"brandName,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
	Domain         *string   `json:"domain,omitempty"`
	ErrorMessage   *string   `json:"errorMessage"`
	FinalUrl       *string   `json:"finalUrl,omitempty"`
	FinalUrlSuffix *string   `json:"finalUrlSuffix,omitempty"`
	Insights       *struct {
		CompetitiveIntensity *string   `json:"competitiveIntensity,omitempty"`
		OpportunityScore     *float32  `json:"opportunityScore,omitempty"`
		Recommendations      *[]string `json:"recommendations,omitempty"`
		RiskLevel            *string   `json:"riskLevel,omitempty"`
	} `json:"insights,omitempty"`
	OfferId       string `json:"offerId"`
	RedirectChain *[]struct {
		StatusCode *int       `json:"statusCode,omitempty"`
		Timestamp  *time.Time `json:"timestamp,omitempty"`
		Url        *string    `json:"url,omitempty"`
	} `json:"redirectChain,omitempty"`
	Score          *float32                `json:"score"`
	SimilarWebData *map[string]interface{} `json:"similarWebData,omitempty"`
	Status         EvaluationResultStatus  `json:"status"`
	UpdatedAt      *time.Time              `json:"updatedAt,omitempty"`
}

// EvaluationResultStatus defines model for EvaluationResult.Status.
type EvaluationResultStatus string

// Offer defines model for Offer.
type Offer struct {
	AdSpend          *float32               `json:"adSpend,omitempty"`
	AvgCpc           *float32               `json:"avgCpc,omitempty"`
	Clicks           *int64                 `json:"clicks,omitempty"`
	CreatedAt        time.Time              `json:"createdAt"`
	Ctr              *float32               `json:"ctr,omitempty"`
	Domain           *string                `json:"domain,omitempty"`
	EvaluationStatus *OfferEvaluationStatus `json:"evaluationStatus,omitempty"`
	FinalUrl         *string                `json:"finalUrl,omitempty"`
	FinalUrlSuffix   *string                `json:"finalUrlSuffix,omitempty"`
	Id               string                 `json:"id"`
	Impressions      *int64                 `json:"impressions,omitempty"`
	LaunchStatus     *OfferLaunchStatus     `json:"launchStatus,omitempty"`
	LinkedAccountIds *[]string              `json:"linkedAccountIds,omitempty"`
	Name             string                 `json:"name"`
	OriginalUrl      string                 `json:"originalUrl"`
	Roas             *float32               `json:"roas,omitempty"`
	SimulationStatus *OfferSimulationStatus `json:"simulationStatus,omitempty"`
	SiterankScore    *float32               `json:"siterankScore"`
	Status           OfferStatus            `json:"status"`
	TargetCountries  *[]string              `json:"targetCountries,omitempty"`
	TotalRevenue     *float32               `json:"totalRevenue,omitempty"`
	UpdatedAt        *time.Time             `json:"updatedAt,omitempty"`
	UserId           string                 `json:"userId"`
}

// OfferEvaluationStatus defines model for Offer.EvaluationStatus.
type OfferEvaluationStatus string

// OfferLaunchStatus defines model for Offer.LaunchStatus.
type OfferLaunchStatus string

// OfferSimulationStatus defines model for Offer.SimulationStatus.
type OfferSimulationStatus string

// OfferStatus defines model for Offer.Status.
type OfferStatus string

// OfferBatchCreateRequest defines model for OfferBatchCreateRequest.
type OfferBatchCreateRequest struct {
	TargetCountries *[]string `json:"targetCountries,omitempty"`
	Urls            []string  `json:"urls"`
}

// OfferCreateRequest defines model for OfferCreateRequest.
type OfferCreateRequest struct {
	Name            string    `json:"name"`
	OriginalUrl     string    `json:"originalUrl"`
	TargetCountries *[]string `json:"targetCountries,omitempty"`
}

// OfferCreatedEvent defines model for OfferCreatedEvent.
type OfferCreatedEvent struct {
	CreatedAt   time.Time `json:"createdAt"`
	Name        string    `json:"name"`
	OfferId     string    `json:"offerId"`
	OriginalUrl string    `json:"originalUrl"`
	Status      string    `json:"status"`
	UserId      string    `json:"userId"`
}

// OfferKpiResponse defines model for OfferKpiResponse.
type OfferKpiResponse struct {
	Days []struct {
		Clicks      int64              `json:"clicks"`
		Date        openapi_types.Date `json:"date"`
		Impressions int64              `json:"impressions"`
		Revenue     float32            `json:"revenue"`
		Spend       float32            `json:"spend"`
	} `json:"days"`
	Summary struct {
		Clicks      int64   `json:"clicks"`
		Impressions int64   `json:"impressions"`
		Revenue     float32 `json:"revenue"`
		Rosc        float32 `json:"rosc"`
		Spend       float32 `json:"spend"`
	} `json:"summary"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// OfferPreferences Per-offer automation preferences. Defaults may be provided by user profile; this endpoint stores overrides.
type OfferPreferences struct {
	// AutoStatusEnabled If true, system may automatically update offer status based on rules; otherwise only suggest changes.
	AutoStatusEnabled bool `json:"autoStatusEnabled"`

	// StatusRules Optional thresholds overriding defaults.
	StatusRules *struct {
		// RoscDeclineDays Days of continuous ROSC decline to suggest/trigger decline.
		RoscDeclineDays *int `json:"roscDeclineDays,omitempty"`

		// ZeroPerfDays Days with zero impressions and zero clicks to suggest/trigger decline.
		ZeroPerfDays *int `json:"zeroPerfDays,omitempty"`
	} `json:"statusRules,omitempty"`
}

// OfferStatusUpdate defines model for OfferStatusUpdate.
type OfferStatusUpdate struct {
	Status string `json:"status"`
}

// OfferStatusUpdated defines model for OfferStatusUpdated.
type OfferStatusUpdated struct {
	From    string                   `json:"from"`
	OfferId string                   `json:"offerId"`
	Status  OfferStatusUpdatedStatus `json:"status"`
	To      string                   `json:"to"`
}

// OfferStatusUpdatedStatus defines model for OfferStatusUpdated.Status.
type OfferStatusUpdatedStatus string

// OfferUpdateRequest defines model for OfferUpdateRequest.
type OfferUpdateRequest struct {
	Name        *string `json:"name,omitempty"`
	OriginalUrl *string `json:"originalUrl,omitempty"`
}

// Revenue defines model for Revenue.
type Revenue struct {
	Amount    float32    `json:"amount"`
	CreatedAt time.Time  `json:"createdAt"`
	Id        string     `json:"id"`
	Note      *string    `json:"note,omitempty"`
	OfferId   string     `json:"offerId"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// InitializeDemoDataJSONBody defines parameters for InitializeDemoData.
type InitializeDemoDataJSONBody struct {
	Modules *[]InitializeDemoDataJSONBodyModules `json:"modules,omitempty"`
}

// InitializeDemoDataJSONBodyModules defines parameters for InitializeDemoData.
type InitializeDemoDataJSONBodyModules string

// LinkOfferAccountJSONBody defines parameters for LinkOfferAccount.
type LinkOfferAccountJSONBody struct {
	AccountId string `json:"accountId"`
}

// UpdateOfferCountriesJSONBody defines parameters for UpdateOfferCountries.
type UpdateOfferCountriesJSONBody struct {
	TargetCountries []string `json:"targetCountries"`
}

// AggregateOfferKpiParams defines parameters for AggregateOfferKpi.
type AggregateOfferKpiParams struct {
	// Date Day to aggregate (UTC). Default today.
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// AddOfferRevenueJSONBody defines parameters for AddOfferRevenue.
type AddOfferRevenueJSONBody struct {
	Amount float32 `json:"amount"`
	Note   *string `json:"note,omitempty"`
}

// InitializeDemoDataJSONRequestBody defines body for InitializeDemoData for application/json ContentType.
type InitializeDemoDataJSONRequestBody InitializeDemoDataJSONBody

// CreateOfferJSONRequestBody defines body for CreateOffer for application/json ContentType.
type CreateOfferJSONRequestBody = OfferCreateRequest

// CreateOffersBatchJSONRequestBody defines body for CreateOffersBatch for application/json ContentType.
type CreateOffersBatchJSONRequestBody = OfferBatchCreateRequest

// UpdateOfferJSONRequestBody defines body for UpdateOffer for application/json ContentType.
type UpdateOfferJSONRequestBody = OfferUpdateRequest

// LinkOfferAccountJSONRequestBody defines body for LinkOfferAccount for application/json ContentType.
type LinkOfferAccountJSONRequestBody LinkOfferAccountJSONBody

// UpdateOfferCountriesJSONRequestBody defines body for UpdateOfferCountries for application/json ContentType.
type UpdateOfferCountriesJSONRequestBody UpdateOfferCountriesJSONBody

// UpdateOfferPreferencesJSONRequestBody defines body for UpdateOfferPreferences for application/json ContentType.
type UpdateOfferPreferencesJSONRequestBody = OfferPreferences

// AddOfferRevenueJSONRequestBody defines body for AddOfferRevenue for application/json ContentType.
type AddOfferRevenueJSONRequestBody AddOfferRevenueJSONBody

// UpdateOfferStatusJSONRequestBody defines body for UpdateOfferStatus for application/json ContentType.
type UpdateOfferStatusJSONRequestBody = OfferStatusUpdate
