// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List recent alerts
	// (GET /api/v1/console/alerts)
	GetAlerts(w http.ResponseWriter, r *http.Request, params GetAlertsParams)
	// Get dashboard statistics (admin only)
	// (GET /api/v1/console/dashboard/stats)
	GetDashboardStats(w http.ResponseWriter, r *http.Request)
	// Get user dashboard (admin only)
	// (GET /api/v1/console/dashboard/{userId})
	GetUserDashboard(w http.ResponseWriter, r *http.Request, userId string)
	// Aggregate incidents by day
	// (GET /api/v1/console/incidents)
	GetIncidents(w http.ResponseWriter, r *http.Request, params GetIncidentsParams)
	// Get navigation configuration for current user
	// (GET /api/v1/console/navigation)
	GetNavigationConfig(w http.ResponseWriter, r *http.Request)
	// List notification rules
	// (GET /api/v1/console/notifications/rules)
	ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams)
	// Create a notification rule
	// (POST /api/v1/console/notifications/rules)
	CreateRule(w http.ResponseWriter, r *http.Request)
	// Evaluate rules against current SLO snapshot
	// (POST /api/v1/console/notifications/rules/evaluate)
	EvaluateRules(w http.ResponseWriter, r *http.Request)
	// Delete rule by id
	// (DELETE /api/v1/console/notifications/rules/{id})
	DeleteRule(w http.ResponseWriter, r *http.Request, id string)
	// Get rule by id
	// (GET /api/v1/console/notifications/rules/{id})
	GetRule(w http.ResponseWriter, r *http.Request, id string)
	// Update rule by id
	// (PUT /api/v1/console/notifications/rules/{id})
	UpdateRule(w http.ResponseWriter, r *http.Request, id string)
	// Get global notification/throttling settings (system or user scope)
	// (GET /api/v1/console/notifications/settings)
	GetNotificationSettings(w http.ResponseWriter, r *http.Request, params GetNotificationSettingsParams)
	// Update global notification/throttling settings (system or user scope)
	// (PUT /api/v1/console/notifications/settings)
	UpdateNotificationSettings(w http.ResponseWriter, r *http.Request, params UpdateNotificationSettingsParams)
	// List Offer KPI DLQ items
	// (GET /api/v1/console/offers/kpi/deadletters)
	ListOfferKpiDLQ(w http.ResponseWriter, r *http.Request, params ListOfferKpiDLQParams)
	// Retry Offer KPI DLQ items
	// (POST /api/v1/console/offers/kpi/retry)
	RetryOfferKpiDLQ(w http.ResponseWriter, r *http.Request)
	// Get SLO snapshot for services
	// (GET /api/v1/console/slo)
	GetSlo(w http.ResponseWriter, r *http.Request, params GetSloParams)
	// Get admin statistics overview
	// (GET /api/v1/console/stats)
	GetAdminStats(w http.ResponseWriter, r *http.Request)
	// List background tasks for current user
	// (GET /api/v1/console/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams)
	// Get task statistics for current user
	// (GET /api/v1/console/tasks/stats)
	GetTaskStats(w http.ResponseWriter, r *http.Request)
	// Stream background tasks updates via SSE for current user
	// (GET /api/v1/console/tasks/stream)
	StreamTasks(w http.ResponseWriter, r *http.Request, params StreamTasksParams)
	// Cancel a task (admin only)
	// (POST /api/v1/console/tasks/{id}/cancel)
	CancelTask(w http.ResponseWriter, r *http.Request, id string)
	// Retry a failed task (admin only)
	// (POST /api/v1/console/tasks/{id}/retry)
	RetryTask(w http.ResponseWriter, r *http.Request, id string)
	// List users (admin only)
	// (GET /api/v1/console/users)
	GetUsers(w http.ResponseWriter, r *http.Request)
	// Get user by ID (admin only)
	// (GET /api/v1/console/users/{id})
	GetUserById(w http.ResponseWriter, r *http.Request, id string)
	// Get user subscription (admin only)
	// (GET /api/v1/console/users/{id}/subscription)
	GetUserSubscription(w http.ResponseWriter, r *http.Request, id string)
	// Update user subscription (admin only)
	// (PUT /api/v1/console/users/{id}/subscription)
	UpdateUserSubscription(w http.ResponseWriter, r *http.Request, id string)
	// Adjust user token balance (admin only)
	// (POST /api/v1/console/users/{id}/tokens)
	AdjustUserTokens(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List recent alerts
// (GET /api/v1/console/alerts)
func (_ Unimplemented) GetAlerts(w http.ResponseWriter, r *http.Request, params GetAlertsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get dashboard statistics (admin only)
// (GET /api/v1/console/dashboard/stats)
func (_ Unimplemented) GetDashboardStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user dashboard (admin only)
// (GET /api/v1/console/dashboard/{userId})
func (_ Unimplemented) GetUserDashboard(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregate incidents by day
// (GET /api/v1/console/incidents)
func (_ Unimplemented) GetIncidents(w http.ResponseWriter, r *http.Request, params GetIncidentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get navigation configuration for current user
// (GET /api/v1/console/navigation)
func (_ Unimplemented) GetNavigationConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List notification rules
// (GET /api/v1/console/notifications/rules)
func (_ Unimplemented) ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a notification rule
// (POST /api/v1/console/notifications/rules)
func (_ Unimplemented) CreateRule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Evaluate rules against current SLO snapshot
// (POST /api/v1/console/notifications/rules/evaluate)
func (_ Unimplemented) EvaluateRules(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete rule by id
// (DELETE /api/v1/console/notifications/rules/{id})
func (_ Unimplemented) DeleteRule(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get rule by id
// (GET /api/v1/console/notifications/rules/{id})
func (_ Unimplemented) GetRule(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update rule by id
// (PUT /api/v1/console/notifications/rules/{id})
func (_ Unimplemented) UpdateRule(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get global notification/throttling settings (system or user scope)
// (GET /api/v1/console/notifications/settings)
func (_ Unimplemented) GetNotificationSettings(w http.ResponseWriter, r *http.Request, params GetNotificationSettingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update global notification/throttling settings (system or user scope)
// (PUT /api/v1/console/notifications/settings)
func (_ Unimplemented) UpdateNotificationSettings(w http.ResponseWriter, r *http.Request, params UpdateNotificationSettingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Offer KPI DLQ items
// (GET /api/v1/console/offers/kpi/deadletters)
func (_ Unimplemented) ListOfferKpiDLQ(w http.ResponseWriter, r *http.Request, params ListOfferKpiDLQParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retry Offer KPI DLQ items
// (POST /api/v1/console/offers/kpi/retry)
func (_ Unimplemented) RetryOfferKpiDLQ(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get SLO snapshot for services
// (GET /api/v1/console/slo)
func (_ Unimplemented) GetSlo(w http.ResponseWriter, r *http.Request, params GetSloParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get admin statistics overview
// (GET /api/v1/console/stats)
func (_ Unimplemented) GetAdminStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List background tasks for current user
// (GET /api/v1/console/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get task statistics for current user
// (GET /api/v1/console/tasks/stats)
func (_ Unimplemented) GetTaskStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream background tasks updates via SSE for current user
// (GET /api/v1/console/tasks/stream)
func (_ Unimplemented) StreamTasks(w http.ResponseWriter, r *http.Request, params StreamTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a task (admin only)
// (POST /api/v1/console/tasks/{id}/cancel)
func (_ Unimplemented) CancelTask(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retry a failed task (admin only)
// (POST /api/v1/console/tasks/{id}/retry)
func (_ Unimplemented) RetryTask(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users (admin only)
// (GET /api/v1/console/users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user by ID (admin only)
// (GET /api/v1/console/users/{id})
func (_ Unimplemented) GetUserById(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user subscription (admin only)
// (GET /api/v1/console/users/{id}/subscription)
func (_ Unimplemented) GetUserSubscription(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user subscription (admin only)
// (PUT /api/v1/console/users/{id}/subscription)
func (_ Unimplemented) UpdateUserSubscription(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Adjust user token balance (admin only)
// (POST /api/v1/console/users/{id}/tokens)
func (_ Unimplemented) AdjustUserTokens(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetAlerts(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlertsParams

	// ------------- Optional query parameter "level" -------------

	err = runtime.BindQueryParameter("form", true, false, "level", r.URL.Query(), &params.Level)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level", Err: err})
		return
	}

	// ------------- Optional query parameter "sinceHours" -------------

	err = runtime.BindQueryParameter("form", true, false, "sinceHours", r.URL.Query(), &params.SinceHours)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sinceHours", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlerts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardStats operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetUserDashboard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserDashboard(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIncidents operation middleware
func (siw *ServerInterfaceWrapper) GetIncidents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIncidentsParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameter("form", true, false, "days", r.URL.Query(), &params.Days)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIncidents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNavigationConfig operation middleware
func (siw *ServerInterfaceWrapper) GetNavigationConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNavigationConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRules operation middleware
func (siw *ServerInterfaceWrapper) ListRules(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRulesParams

	// ------------- Optional query parameter "service" -------------

	err = runtime.BindQueryParameter("form", true, false, "service", r.URL.Query(), &params.Service)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Optional query parameter "metric" -------------

	err = runtime.BindQueryParameter("form", true, false, "metric", r.URL.Query(), &params.Metric)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metric", Err: err})
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameter("form", true, false, "enabled", r.URL.Query(), &params.Enabled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRule operation middleware
func (siw *ServerInterfaceWrapper) CreateRule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EvaluateRules operation middleware
func (siw *ServerInterfaceWrapper) EvaluateRules(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EvaluateRules(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRule operation middleware
func (siw *ServerInterfaceWrapper) GetRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNotificationSettings operation middleware
func (siw *ServerInterfaceWrapper) GetNotificationSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNotificationSettingsParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNotificationSettings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNotificationSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateNotificationSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateNotificationSettingsParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNotificationSettings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOfferKpiDLQ operation middleware
func (siw *ServerInterfaceWrapper) ListOfferKpiDLQ(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOfferKpiDLQParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOfferKpiDLQ(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RetryOfferKpiDLQ operation middleware
func (siw *ServerInterfaceWrapper) RetryOfferKpiDLQ(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RetryOfferKpiDLQ(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSlo operation middleware
func (siw *ServerInterfaceWrapper) GetSlo(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSloParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", r.URL.Query(), &params.Force)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSlo(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminStats operation middleware
func (siw *ServerInterfaceWrapper) GetAdminStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTasksParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskStats operation middleware
func (siw *ServerInterfaceWrapper) GetTaskStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamTasks operation middleware
func (siw *ServerInterfaceWrapper) StreamTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamTasksParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelTask operation middleware
func (siw *ServerInterfaceWrapper) CancelTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RetryTask operation middleware
func (siw *ServerInterfaceWrapper) RetryTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RetryTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserSubscription operation middleware
func (siw *ServerInterfaceWrapper) GetUserSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserSubscription(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserSubscription operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserSubscription(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdjustUserTokens operation middleware
func (siw *ServerInterfaceWrapper) AdjustUserTokens(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdjustUserTokens(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/alerts", wrapper.GetAlerts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/dashboard/stats", wrapper.GetDashboardStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/dashboard/{userId}", wrapper.GetUserDashboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/incidents", wrapper.GetIncidents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/navigation", wrapper.GetNavigationConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/notifications/rules", wrapper.ListRules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/console/notifications/rules", wrapper.CreateRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/console/notifications/rules/evaluate", wrapper.EvaluateRules)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/console/notifications/rules/{id}", wrapper.DeleteRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/notifications/rules/{id}", wrapper.GetRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/console/notifications/rules/{id}", wrapper.UpdateRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/notifications/settings", wrapper.GetNotificationSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/console/notifications/settings", wrapper.UpdateNotificationSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/offers/kpi/deadletters", wrapper.ListOfferKpiDLQ)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/console/offers/kpi/retry", wrapper.RetryOfferKpiDLQ)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/slo", wrapper.GetSlo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/stats", wrapper.GetAdminStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/tasks", wrapper.ListTasks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/tasks/stats", wrapper.GetTaskStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/tasks/stream", wrapper.StreamTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/console/tasks/{id}/cancel", wrapper.CancelTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/console/tasks/{id}/retry", wrapper.RetryTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/users/{id}", wrapper.GetUserById)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/console/users/{id}/subscription", wrapper.GetUserSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/console/users/{id}/subscription", wrapper.UpdateUserSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/console/users/{id}/tokens", wrapper.AdjustUserTokens)
	})

	return r
}
