// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for TaskStatus.
const (
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusFailed    TaskStatus = "failed"
	TaskStatusPending   TaskStatus = "pending"
	TaskStatusRunning   TaskStatus = "running"
)

// Defines values for GetAlertsParamsLevel.
const (
	Error GetAlertsParamsLevel = "error"
	Warn  GetAlertsParamsLevel = "warn"
)

// Defines values for CreateRuleJSONBodyComparator.
const (
	Eq CreateRuleJSONBodyComparator = "eq"
	Ge CreateRuleJSONBodyComparator = "ge"
	Gt CreateRuleJSONBodyComparator = "gt"
	Le CreateRuleJSONBodyComparator = "le"
	Lt CreateRuleJSONBodyComparator = "lt"
	Ne CreateRuleJSONBodyComparator = "ne"
)

// Defines values for CreateRuleJSONBodyScope.
const (
	CreateRuleJSONBodyScopeSystem CreateRuleJSONBodyScope = "system"
	CreateRuleJSONBodyScopeUser   CreateRuleJSONBodyScope = "user"
)

// Defines values for GetNotificationSettingsParamsScope.
const (
	GetNotificationSettingsParamsScopeSystem GetNotificationSettingsParamsScope = "system"
	GetNotificationSettingsParamsScopeUser   GetNotificationSettingsParamsScope = "user"
)

// Defines values for UpdateNotificationSettingsParamsScope.
const (
	UpdateNotificationSettingsParamsScopeSystem UpdateNotificationSettingsParamsScope = "system"
	UpdateNotificationSettingsParamsScopeUser   UpdateNotificationSettingsParamsScope = "user"
)

// Defines values for GetSloParamsForce.
const (
	N1 GetSloParamsForce = "1"
)

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusCompleted ListTasksParamsStatus = "completed"
	ListTasksParamsStatusFailed    ListTasksParamsStatus = "failed"
	ListTasksParamsStatusPending   ListTasksParamsStatus = "pending"
	ListTasksParamsStatusRunning   ListTasksParamsStatus = "running"
)

// Defines values for StreamTasksParamsStatus.
const (
	Completed StreamTasksParamsStatus = "completed"
	Failed    StreamTasksParamsStatus = "failed"
	Pending   StreamTasksParamsStatus = "pending"
	Running   StreamTasksParamsStatus = "running"
)

// NotificationSettings defines model for NotificationSettings.
type NotificationSettings struct {
	Channels *struct {
		Email   *bool `json:"email,omitempty"`
		InApp   *bool `json:"inApp,omitempty"`
		Webhook *bool `json:"webhook,omitempty"`
	} `json:"channels,omitempty"`

	// Enabled Master switch for notifications/alerts.
	Enabled *bool `json:"enabled,omitempty"`

	// GroupWindowSec Window to group similar alerts for de-duplication.
	GroupWindowSec *int `json:"groupWindowSec,omitempty"`

	// MinConfidence Minimum confidence to trigger alert delivery.
	MinConfidence *float32 `json:"minConfidence,omitempty"`

	// ThrottlePerMinute Max number of alerts delivered per minute (0 = unlimited).
	ThrottlePerMinute *int `json:"throttlePerMinute,omitempty"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Status    string     `json:"status"`
	Tier      string     `json:"tier"`
}

// SubscriptionUpdate defines model for SubscriptionUpdate.
type SubscriptionUpdate struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Tier      string     `json:"tier"`
}

// Task defines model for Task.
type Task struct {
	CompletedAt *time.Time              `json:"completedAt"`
	CreatedAt   time.Time               `json:"createdAt"`
	Error       *string                 `json:"error"`
	Id          string                  `json:"id"`
	Payload     *map[string]interface{} `json:"payload,omitempty"`
	Result      *map[string]interface{} `json:"result"`
	StartedAt   *time.Time              `json:"startedAt"`
	Status      TaskStatus              `json:"status"`
	Type        string                  `json:"type"`
	UserId      string                  `json:"userId"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// User defines model for User.
type User struct {
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	Email            string     `json:"email"`
	Id               string     `json:"id"`
	SubscriptionTier *string    `json:"subscriptionTier,omitempty"`
	TokenBalance     *int       `json:"tokenBalance,omitempty"`
}

// GetAlertsParams defines parameters for GetAlerts.
type GetAlertsParams struct {
	Level      *GetAlertsParamsLevel `form:"level,omitempty" json:"level,omitempty"`
	SinceHours *int                  `form:"sinceHours,omitempty" json:"sinceHours,omitempty"`
	Limit      *int                  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetAlertsParamsLevel defines parameters for GetAlerts.
type GetAlertsParamsLevel string

// GetIncidentsParams defines parameters for GetIncidents.
type GetIncidentsParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListRulesParams defines parameters for ListRules.
type ListRulesParams struct {
	Service *string `form:"service,omitempty" json:"service,omitempty"`
	Metric  *string `form:"metric,omitempty" json:"metric,omitempty"`
	Scope   *string `form:"scope,omitempty" json:"scope,omitempty"`
	Enabled *bool   `form:"enabled,omitempty" json:"enabled,omitempty"`
}

// CreateRuleJSONBody defines parameters for CreateRule.
type CreateRuleJSONBody struct {
	Comparator *CreateRuleJSONBodyComparator `json:"comparator,omitempty"`
	Enabled    *bool                         `json:"enabled,omitempty"`
	Metric     *string                       `json:"metric,omitempty"`
	Params     *map[string]interface{}       `json:"params,omitempty"`
	Scope      *CreateRuleJSONBodyScope      `json:"scope,omitempty"`
	Service    *string                       `json:"service,omitempty"`
	Threshold  *float32                      `json:"threshold,omitempty"`
	UserID     *string                       `json:"userID,omitempty"`
	WindowSec  *int                          `json:"windowSec,omitempty"`
}

// CreateRuleJSONBodyComparator defines parameters for CreateRule.
type CreateRuleJSONBodyComparator string

// CreateRuleJSONBodyScope defines parameters for CreateRule.
type CreateRuleJSONBodyScope string

// UpdateRuleJSONBody defines parameters for UpdateRule.
type UpdateRuleJSONBody map[string]interface{}

// GetNotificationSettingsParams defines parameters for GetNotificationSettings.
type GetNotificationSettingsParams struct {
	Scope *GetNotificationSettingsParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetNotificationSettingsParamsScope defines parameters for GetNotificationSettings.
type GetNotificationSettingsParamsScope string

// UpdateNotificationSettingsParams defines parameters for UpdateNotificationSettings.
type UpdateNotificationSettingsParams struct {
	Scope *UpdateNotificationSettingsParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
}

// UpdateNotificationSettingsParamsScope defines parameters for UpdateNotificationSettings.
type UpdateNotificationSettingsParamsScope string

// ListOfferKpiDLQParams defines parameters for ListOfferKpiDLQ.
type ListOfferKpiDLQParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// RetryOfferKpiDLQJSONBody defines parameters for RetryOfferKpiDLQ.
type RetryOfferKpiDLQJSONBody struct {
	Id  *string `json:"id,omitempty"`
	Max *int    `json:"max,omitempty"`
}

// GetSloParams defines parameters for GetSlo.
type GetSloParams struct {
	Force *GetSloParamsForce `form:"force,omitempty" json:"force,omitempty"`
}

// GetSloParamsForce defines parameters for GetSlo.
type GetSloParamsForce string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// StreamTasksParams defines parameters for StreamTasks.
type StreamTasksParams struct {
	Status *StreamTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// StreamTasksParamsStatus defines parameters for StreamTasks.
type StreamTasksParamsStatus string

// AdjustUserTokensJSONBody defines parameters for AdjustUserTokens.
type AdjustUserTokensJSONBody struct {
	Amount      int     `json:"amount"`
	Description *string `json:"description,omitempty"`
}

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody CreateRuleJSONBody

// UpdateRuleJSONRequestBody defines body for UpdateRule for application/json ContentType.
type UpdateRuleJSONRequestBody UpdateRuleJSONBody

// UpdateNotificationSettingsJSONRequestBody defines body for UpdateNotificationSettings for application/json ContentType.
type UpdateNotificationSettingsJSONRequestBody = NotificationSettings

// RetryOfferKpiDLQJSONRequestBody defines body for RetryOfferKpiDLQ for application/json ContentType.
type RetryOfferKpiDLQJSONRequestBody RetryOfferKpiDLQJSONBody

// UpdateUserSubscriptionJSONRequestBody defines body for UpdateUserSubscription for application/json ContentType.
type UpdateUserSubscriptionJSONRequestBody = SubscriptionUpdate

// AdjustUserTokensJSONRequestBody defines body for AdjustUserTokens for application/json ContentType.
type AdjustUserTokensJSONRequestBody AdjustUserTokensJSONBody
