timeout: "3600s"
options:
  logging: GCS_ONLY
logsBucket: gs://adsai-build-logs-asia-northeast1/logs
substitutions:
  _IMAGE: "asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/browser-exec:preview-latest"
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - build
      - '-f'
      - 'Dockerfile'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'

