#!/bin/bash

# 检查 OAuth 客户端的重定向 URI 配置

PROJECT_ID="your-gcp-project-id"
CLIENT_ID="644672509127-sj0oe3shl7nltvn1agiuf1rv2vqgfsuj.apps.googleusercontent.com"

echo "======================================"
echo "检查 OAuth 客户端重定向 URI 配置"
echo "======================================"
echo ""
echo "Client ID: $CLIENT_ID"
echo ""
echo "请访问 GCP Console 检查重定向 URI："
echo "https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
echo ""
echo "必须包含以下 Firebase Auth 回调 URL："
echo ""
echo "✅ 必需的重定向 URI："
echo "   https://preview.example.com/__/auth/handler"
echo "   https://preview.example.com/__/auth/handler"
echo "   https://www.example.com/__/auth/handler"
echo "   https://example.com/__/auth/handler"
echo ""
echo "❌ 当前可能缺少的："
echo "   Firebase 默认回调 URL (如果前端通过 Firebase Hosting 部署)"
echo ""
echo "错误信息表明："
echo "   error=invalid_client&error_description=Unauthorized"
echo "   OAuth2 redirect uri is: https://preview.example.com/__/auth/handler"
echo ""
echo "这说明 Google 在验证重定向 URI 时失败了。"
echo ""
echo "可能的原因："
echo "1. 重定向 URI 列表中缺少 https://preview.example.com/__/auth/handler"
echo "2. URI 格式不正确（如多余的空格、换行符）"
echo "3. OAuth 客户端被禁用或删除"
echo ""
