timeout: "3600s"
options:
  logging: GCS_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','apps/frontend/Dockerfile','-t','asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/frontend:latest','.']
images: ['asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/frontend:latest']
