steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','services/adscenter/Dockerfile','-t','asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/adscenter:latest','.']
images: ['asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/adscenter:latest']
