steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','services/offer/Dockerfile','-t','asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/offer:latest','.']
images: ['asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/offer:latest']
