steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','services/workflow/Dockerfile','-t','asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/workflow:latest','.']
images: ['asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/workflow:latest']
