apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: db-migrator-preview
  labels:
    component: db-migrator
    environment: preview
  annotations:
    run.googleapis.com/vpc-access-connector: projects/your-gcp-project-id/locations/asia-northeast1/connectors/cr-conn-default-ane1
    run.googleapis.com/vpc-access-egress: all-traffic
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: projects/your-gcp-project-id/locations/asia-northeast1/connectors/cr-conn-default-ane1
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      template:
        spec:
          serviceAccountName: service-account@your-gcp-project-id.iam.gserviceaccount.com
          containers:
          - name: db-migrator
            image: asia-northeast1-docker.pkg.dev/your-gcp-project-id/adsai-services/db-migrator:preview-latest
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: DATABASE_URL
                  key: latest
            - name: SCHEMAS_DIR
              value: /app/schemas/sql
            resources:
              limits:
                cpu: "1"
                memory: 512Mi
          timeoutSeconds: 600
          maxRetries: 1
