// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all permission configurations
	// (GET /admin/permissions)
	GetAllPermissions(w http.ResponseWriter, r *http.Request)
	// Get all token cost configurations
	// (GET /admin/token-costs)
	GetAllTokenCosts(w http.ResponseWriter, r *http.Request)
	// Get all subscription configuration (permissions, token costs, pricing)
	// (GET /config/all)
	GetAllsubscriptionsConfig(w http.ResponseWriter, r *http.Request)
	// Get configuration change history
	// (GET /config/history)
	GetConfigHistory(w http.ResponseWriter, r *http.Request, params GetConfigHistoryParams)
	// Get subscription pricing configuration
	// (GET /config/pricing)
	GetPricingConfig(w http.ResponseWriter, r *http.Request)
	// Update pricing configuration for a plan
	// (PUT /config/pricing/{plan})
	UpdatePricingConfig(w http.ResponseWriter, r *http.Request, plan string)
	// Get current subscription
	// (GET /subscription)
	Getsubscriptions(w http.ResponseWriter, r *http.Request)
	// Get current user subscription details
	// (GET /subscriptions/me)
	GetsubscriptionsMe(w http.ResponseWriter, r *http.Request)
	// Get current user's token balance
	// (GET /tokens/balance)
	GetTokenBalance(w http.ResponseWriter, r *http.Request)
	// Commit reserved tokens for a task
	// (POST /tokens/commit)
	CommitTokens(w http.ResponseWriter, r *http.Request)
	// Token balance consistency across aggregates
	// (GET /tokens/consistency)
	GetTokenConsistency(w http.ResponseWriter, r *http.Request)
	// Compute consistency repair plan (admin)
	// (GET /tokens/consistency/plan)
	GetTokenConsistencyPlan(w http.ResponseWriter, r *http.Request, params GetTokenConsistencyPlanParams)
	// Apply consistency repair (admin)
	// (POST /tokens/consistency/repair)
	PostTokenConsistencyRepair(w http.ResponseWriter, r *http.Request)
	// Credit purchased tokens (pool-aware, idempotent)
	// (POST /tokens/credit/purchased)
	CreditPurchasedTokens(w http.ResponseWriter, r *http.Request)
	// Credit subscription tokens (pool-aware, idempotent)
	// (POST /tokens/credit/subscription)
	CreditsubscriptionsTokens(w http.ResponseWriter, r *http.Request)
	// Release previously reserved tokens
	// (POST /tokens/release)
	ReleaseTokens(w http.ResponseWriter, r *http.Request)
	// Reserve tokens for a task
	// (POST /tokens/reserve)
	ReserveTokens(w http.ResponseWriter, r *http.Request)
	// List token transactions (last 50)
	// (GET /tokens/transactions)
	Listtoken_transactionss(w http.ResponseWriter, r *http.Request)
	// Get token usage summary for current user
	// (GET /tokens/usage)
	GetTokenUsage(w http.ResponseWriter, r *http.Request, params GetTokenUsageParams)
	// Convert trial to paid subscription
	// (POST /trial/convert)
	ConvertTrialTosubscriptions(w http.ResponseWriter, r *http.Request)
	// Start a trial subscription
	// (POST /trial/start)
	StartTrialsubscriptions(w http.ResponseWriter, r *http.Request)
	// Get current trial subscription status
	// (GET /trial/status)
	GetTrialStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all permission configurations
// (GET /admin/permissions)
func (_ Unimplemented) GetAllPermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all token cost configurations
// (GET /admin/token-costs)
func (_ Unimplemented) GetAllTokenCosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all subscription configuration (permissions, token costs, pricing)
// (GET /config/all)
func (_ Unimplemented) GetAllsubscriptionsConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get configuration change history
// (GET /config/history)
func (_ Unimplemented) GetConfigHistory(w http.ResponseWriter, r *http.Request, params GetConfigHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get subscription pricing configuration
// (GET /config/pricing)
func (_ Unimplemented) GetPricingConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update pricing configuration for a plan
// (PUT /config/pricing/{plan})
func (_ Unimplemented) UpdatePricingConfig(w http.ResponseWriter, r *http.Request, plan string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current subscription
// (GET /subscription)
func (_ Unimplemented) Getsubscriptions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user subscription details
// (GET /subscriptions/me)
func (_ Unimplemented) GetsubscriptionsMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user's token balance
// (GET /tokens/balance)
func (_ Unimplemented) GetTokenBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Commit reserved tokens for a task
// (POST /tokens/commit)
func (_ Unimplemented) CommitTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Token balance consistency across aggregates
// (GET /tokens/consistency)
func (_ Unimplemented) GetTokenConsistency(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Compute consistency repair plan (admin)
// (GET /tokens/consistency/plan)
func (_ Unimplemented) GetTokenConsistencyPlan(w http.ResponseWriter, r *http.Request, params GetTokenConsistencyPlanParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Apply consistency repair (admin)
// (POST /tokens/consistency/repair)
func (_ Unimplemented) PostTokenConsistencyRepair(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Credit purchased tokens (pool-aware, idempotent)
// (POST /tokens/credit/purchased)
func (_ Unimplemented) CreditPurchasedTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Credit subscription tokens (pool-aware, idempotent)
// (POST /tokens/credit/subscription)
func (_ Unimplemented) CreditsubscriptionsTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Release previously reserved tokens
// (POST /tokens/release)
func (_ Unimplemented) ReleaseTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reserve tokens for a task
// (POST /tokens/reserve)
func (_ Unimplemented) ReserveTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List token transactions (last 50)
// (GET /tokens/transactions)
func (_ Unimplemented) Listtoken_transactionss(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get token usage summary for current user
// (GET /tokens/usage)
func (_ Unimplemented) GetTokenUsage(w http.ResponseWriter, r *http.Request, params GetTokenUsageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Convert trial to paid subscription
// (POST /trial/convert)
func (_ Unimplemented) ConvertTrialTosubscriptions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a trial subscription
// (POST /trial/start)
func (_ Unimplemented) StartTrialsubscriptions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current trial subscription status
// (GET /trial/status)
func (_ Unimplemented) GetTrialStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAllPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetAllPermissions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllPermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllTokenCosts operation middleware
func (siw *ServerInterfaceWrapper) GetAllTokenCosts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllTokenCosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllsubscriptionsConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAllsubscriptionsConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllsubscriptionsConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConfigHistory operation middleware
func (siw *ServerInterfaceWrapper) GetConfigHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetConfigHistoryParams

	// ------------- Optional query parameter "configType" -------------

	err = runtime.BindQueryParameter("form", true, false, "configType", r.URL.Query(), &params.ConfigType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "configType", Err: err})
		return
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "startDate", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startDate", Err: err})
		return
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "endDate", r.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endDate", Err: err})
		return
	}

	// ------------- Optional query parameter "changedBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "changedBy", r.URL.Query(), &params.ChangedBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "changedBy", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfigHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPricingConfig operation middleware
func (siw *ServerInterfaceWrapper) GetPricingConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPricingConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePricingConfig operation middleware
func (siw *ServerInterfaceWrapper) UpdatePricingConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "plan" -------------
	var plan string

	err = runtime.BindStyledParameterWithOptions("simple", "plan", chi.URLParam(r, "plan"), &plan, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "plan", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePricingConfig(w, r, plan)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Getsubscriptions operation middleware
func (siw *ServerInterfaceWrapper) Getsubscriptions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Getsubscriptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetsubscriptionsMe operation middleware
func (siw *ServerInterfaceWrapper) GetsubscriptionsMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetsubscriptionsMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTokenBalance operation middleware
func (siw *ServerInterfaceWrapper) GetTokenBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTokenBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommitTokens operation middleware
func (siw *ServerInterfaceWrapper) CommitTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommitTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTokenConsistency operation middleware
func (siw *ServerInterfaceWrapper) GetTokenConsistency(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTokenConsistency(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTokenConsistencyPlan operation middleware
func (siw *ServerInterfaceWrapper) GetTokenConsistencyPlan(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTokenConsistencyPlanParams

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTokenConsistencyPlan(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTokenConsistencyRepair operation middleware
func (siw *ServerInterfaceWrapper) PostTokenConsistencyRepair(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTokenConsistencyRepair(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreditPurchasedTokens operation middleware
func (siw *ServerInterfaceWrapper) CreditPurchasedTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreditPurchasedTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreditsubscriptionsTokens operation middleware
func (siw *ServerInterfaceWrapper) CreditsubscriptionsTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreditsubscriptionsTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReleaseTokens operation middleware
func (siw *ServerInterfaceWrapper) ReleaseTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReleaseTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReserveTokens operation middleware
func (siw *ServerInterfaceWrapper) ReserveTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReserveTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Listtoken_transactionss operation middleware
func (siw *ServerInterfaceWrapper) Listtoken_transactionss(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Listtoken_transactionss(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTokenUsage operation middleware
func (siw *ServerInterfaceWrapper) GetTokenUsage(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTokenUsageParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameter("form", true, false, "days", r.URL.Query(), &params.Days)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTokenUsage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConvertTrialTosubscriptions operation middleware
func (siw *ServerInterfaceWrapper) ConvertTrialTosubscriptions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConvertTrialTosubscriptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartTrialsubscriptions operation middleware
func (siw *ServerInterfaceWrapper) StartTrialsubscriptions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartTrialsubscriptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrialStatus operation middleware
func (siw *ServerInterfaceWrapper) GetTrialStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrialStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/permissions", wrapper.GetAllPermissions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/token-costs", wrapper.GetAllTokenCosts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config/all", wrapper.GetAllsubscriptionsConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config/history", wrapper.GetConfigHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config/pricing", wrapper.GetPricingConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/config/pricing/{plan}", wrapper.UpdatePricingConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscription", wrapper.Getsubscriptions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscriptions/me", wrapper.GetsubscriptionsMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tokens/balance", wrapper.GetTokenBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tokens/commit", wrapper.CommitTokens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tokens/consistency", wrapper.GetTokenConsistency)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tokens/consistency/plan", wrapper.GetTokenConsistencyPlan)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tokens/consistency/repair", wrapper.PostTokenConsistencyRepair)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tokens/credit/purchased", wrapper.CreditPurchasedTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tokens/credit/subscription", wrapper.CreditsubscriptionsTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tokens/release", wrapper.ReleaseTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tokens/reserve", wrapper.ReserveTokens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tokens/transactions", wrapper.Listtoken_transactionss)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tokens/usage", wrapper.GetTokenUsage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trial/convert", wrapper.ConvertTrialTosubscriptions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trial/start", wrapper.StartTrialsubscriptions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trial/status", wrapper.GetTrialStatus)
	})

	return r
}
