// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for TrialsubscriptionsPlanType.
const (
	TrialsubscriptionsPlanTypeElite        TrialsubscriptionsPlanType = "elite"
	TrialsubscriptionsPlanTypeProfessional TrialsubscriptionsPlanType = "professional"
)

// Defines values for TrialsubscriptionsStatus.
const (
	Active    TrialsubscriptionsStatus = "active"
	Converted TrialsubscriptionsStatus = "converted"
	Expired   TrialsubscriptionsStatus = "expired"
)

// Defines values for ConvertTrialTosubscriptionsJSONBodyPlanType.
const (
	ConvertTrialTosubscriptionsJSONBodyPlanTypeElite        ConvertTrialTosubscriptionsJSONBodyPlanType = "elite"
	ConvertTrialTosubscriptionsJSONBodyPlanTypeProfessional ConvertTrialTosubscriptionsJSONBodyPlanType = "professional"
)

// Defines values for StartTrialsubscriptionsJSONBodyPlanType.
const (
	Elite        StartTrialsubscriptionsJSONBodyPlanType = "elite"
	Professional StartTrialsubscriptionsJSONBodyPlanType = "professional"
)

// ConfigHistoryItem defines model for ConfigHistoryItem.
type ConfigHistoryItem struct {
	Action         string                  `json:"action"`
	ChangedAt      time.Time               `json:"changedAt"`
	ChangedBy      *string                 `json:"changedBy,omitempty"`
	ChangedByEmail *string                 `json:"changedByEmail,omitempty"`
	ConfigId       string                  `json:"configId"`
	ConfigType     string                  `json:"configType"`
	Id             string                  `json:"id"`
	NewValue       map[string]interface{}  `json:"newValue"`
	OldValue       *map[string]interface{} `json:"oldValue,omitempty"`
}

// subscriptions defines model for subscriptions.
type subscriptions struct {
	CurrentPeriodEnd time.Time `json:"currentPeriodEnd"`
	Id               string    `json:"id"`
	PlanName         string    `json:"plan_name"`
	Status           string    `json:"status"`
}

// token_transactions defines model for token_transactions.
type token_transactions struct {
	Amount      int       `json:"amount"`
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	Id          string    `json:"id"`
	Type        string    `json:"type"`
}

// Trialsubscriptions defines model for Trialsubscriptions.
type Trialsubscriptions struct {
	ConvertedAt *time.Time                `json:"convertedAt,omitempty"`
	ExpiresAt   time.Time                 `json:"expiresAt"`
	Id          string                    `json:"id"`
	PlanType    TrialsubscriptionsPlanType `json:"planType"`
	StartedAt   time.Time                 `json:"startedAt"`
	Status      TrialsubscriptionsStatus   `json:"status"`
	TokenQuota  int                       `json:"tokenQuota"`
	UserId      string                    `json:"user_id"`
}

// TrialsubscriptionsPlanType defines model for Trialsubscriptions.PlanType.
type TrialsubscriptionsPlanType string

// TrialsubscriptionsStatus defines model for Trialsubscriptions.Status.
type TrialsubscriptionsStatus string

// GetConfigHistoryParams defines parameters for GetConfigHistory.
type GetConfigHistoryParams struct {
	ConfigType *string             `form:"configType,omitempty" json:"configType,omitempty"`
	StartDate  *openapi_types.Date `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate    *openapi_types.Date `form:"endDate,omitempty" json:"endDate,omitempty"`
	ChangedBy  *string             `form:"changedBy,omitempty" json:"changedBy,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// UpdatePricingConfigJSONBody defines parameters for UpdatePricingConfig.
type UpdatePricingConfigJSONBody struct {
	MonthlyPrice float32 `json:"monthlyPrice"`
	TokenQuota   int     `json:"tokenQuota"`
	YearlyPrice  float32 `json:"yearlyPrice"`
}

// CommitTokensJSONBody defines parameters for CommitTokens.
type CommitTokensJSONBody struct {
	Amount int     `json:"amount"`
	TaskId *string `json:"taskId,omitempty"`
	TxId   *string `json:"txId,omitempty"`
}

// GetTokenConsistencyPlanParams defines parameters for GetTokenConsistencyPlan.
type GetTokenConsistencyPlanParams struct {
	UserId *string `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// PostTokenConsistencyRepairJSONBody defines parameters for PostTokenConsistencyRepair.
type PostTokenConsistencyRepairJSONBody struct {
	Confirm *bool  `json:"confirm,omitempty"`
	DryRun  *bool  `json:"dryRun,omitempty"`
	UserId  string `json:"user_id"`
}

// CreditPurchasedTokensJSONBody defines parameters for CreditPurchasedTokens.
type CreditPurchasedTokensJSONBody struct {
	Amount      int                     `json:"amount"`
	Description *string                 `json:"description,omitempty"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
}

// CreditsubscriptionsTokensJSONBody defines parameters for CreditsubscriptionsTokens.
type CreditsubscriptionsTokensJSONBody struct {
	Amount      int                                        `json:"amount"`
	Description *string                                    `json:"description,omitempty"`
	Metadata    *CreditsubscriptionsTokensJSONBody_Metadata `json:"metadata,omitempty"`
}

// CreditsubscriptionsTokensJSONBody_Metadata defines parameters for CreditsubscriptionsTokens.
type CreditsubscriptionsTokensJSONBody_Metadata struct {
	ExpiresAt            *time.Time             `json:"expiresAt,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ReleaseTokensJSONBody defines parameters for ReleaseTokens.
type ReleaseTokensJSONBody struct {
	Amount int     `json:"amount"`
	TaskId *string `json:"taskId,omitempty"`
	TxId   *string `json:"txId,omitempty"`
}

// ReserveTokensJSONBody defines parameters for ReserveTokens.
type ReserveTokensJSONBody struct {
	Amount int     `json:"amount"`
	TaskId *string `json:"taskId,omitempty"`
}

// GetTokenUsageParams defines parameters for GetTokenUsage.
type GetTokenUsageParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ConvertTrialTosubscriptionsJSONBody defines parameters for ConvertTrialTosubscriptions.
type ConvertTrialTosubscriptionsJSONBody struct {
	PaymentMethodId string                                     `json:"paymentMethodId"`
	PlanType        ConvertTrialTosubscriptionsJSONBodyPlanType `json:"planType"`
}

// ConvertTrialTosubscriptionsJSONBodyPlanType defines parameters for ConvertTrialTosubscriptions.
type ConvertTrialTosubscriptionsJSONBodyPlanType string

// StartTrialsubscriptionsJSONBody defines parameters for StartTrialsubscriptions.
type StartTrialsubscriptionsJSONBody struct {
	DurationDays *int                                   `json:"durationDays,omitempty"`
	PlanType     StartTrialsubscriptionsJSONBodyPlanType `json:"planType"`
}

// StartTrialsubscriptionsJSONBodyPlanType defines parameters for StartTrialsubscriptions.
type StartTrialsubscriptionsJSONBodyPlanType string

// UpdatePricingConfigJSONRequestBody defines body for UpdatePricingConfig for application/json ContentType.
type UpdatePricingConfigJSONRequestBody UpdatePricingConfigJSONBody

// CommitTokensJSONRequestBody defines body for CommitTokens for application/json ContentType.
type CommitTokensJSONRequestBody CommitTokensJSONBody

// PostTokenConsistencyRepairJSONRequestBody defines body for PostTokenConsistencyRepair for application/json ContentType.
type PostTokenConsistencyRepairJSONRequestBody PostTokenConsistencyRepairJSONBody

// CreditPurchasedTokensJSONRequestBody defines body for CreditPurchasedTokens for application/json ContentType.
type CreditPurchasedTokensJSONRequestBody CreditPurchasedTokensJSONBody

// CreditsubscriptionsTokensJSONRequestBody defines body for CreditsubscriptionsTokens for application/json ContentType.
type CreditsubscriptionsTokensJSONRequestBody CreditsubscriptionsTokensJSONBody

// ReleaseTokensJSONRequestBody defines body for ReleaseTokens for application/json ContentType.
type ReleaseTokensJSONRequestBody ReleaseTokensJSONBody

// ReserveTokensJSONRequestBody defines body for ReserveTokens for application/json ContentType.
type ReserveTokensJSONRequestBody ReserveTokensJSONBody

// ConvertTrialTosubscriptionsJSONRequestBody defines body for ConvertTrialTosubscriptions for application/json ContentType.
type ConvertTrialTosubscriptionsJSONRequestBody ConvertTrialTosubscriptionsJSONBody

// StartTrialsubscriptionsJSONRequestBody defines body for StartTrialsubscriptions for application/json ContentType.
type StartTrialsubscriptionsJSONRequestBody StartTrialsubscriptionsJSONBody

// Getter for additional properties for CreditsubscriptionsTokensJSONBody_Metadata. Returns the specified
// element and whether it was found
func (a CreditsubscriptionsTokensJSONBody_Metadata) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CreditsubscriptionsTokensJSONBody_Metadata
func (a *CreditsubscriptionsTokensJSONBody_Metadata) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CreditsubscriptionsTokensJSONBody_Metadata to handle AdditionalProperties
func (a *CreditsubscriptionsTokensJSONBody_Metadata) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["expiresAt"]; found {
		err = json.Unmarshal(raw, &a.ExpiresAt)
		if err != nil {
			return fmt.Errorf("error reading 'expiresAt': %w", err)
		}
		delete(object, "expiresAt")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CreditsubscriptionsTokensJSONBody_Metadata to handle AdditionalProperties
func (a CreditsubscriptionsTokensJSONBody_Metadata) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ExpiresAt != nil {
		object["expiresAt"], err = json.Marshal(a.ExpiresAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expiresAt': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
